### ISSUE TITLE
Parser Plan

### ISSUE THREAD

**Issue by caffeine-addictt** [caffeine-addictt/sharkalyze#19]
## Stage 1 (less efficient MVP - sync)

- [x] Classes should be stripped from html content
- [x] Cascade URL fetching (script tags, js sources)
- [x] Caching previously fetched (skip on cache hit)

## Stage 2

- [x] Tokio async
- [ ] Limit concurrency
- [x] Parallel
